# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: vsts-habitat-install@3

- task: vsts-habitat-signing-key@3
  inputs:
    habitatOrigin: 'rycar-hab'
    taskAction: 'install'

- script: |
    hab pkg list
  displayName: 'Test hab binary'
